--- SITIO A
-- CREAR MI LINKED SERVER

EXEC sp_addlinkedserver
@server = 'LS_SITIO_B',
@srvproduct = '',
@provider = 'SQLNCLI',
@datasrc = 'localhost\SITIO_AD_B',
@provstr = N'encrypt=yes;trustservercertificate=yes'

EXEC sp_addlinkedsrvlogin
@rmtsrvname = 'LS_SITIO_B',
@useself = 'false',
@rmtuser = 'sa',
@rmtpassword = 'sa'

select * from LS_SITIO_B.MEDICITY_B.dbo.DIAGNOSTICO_SB;
select * from LS_SITIO_B.MEDICITY_B.dbo.DOCTOR_SB;
select * from LS_SITIO_B.MEDICITY_B.dbo.ESPECIALIDAD_SB;

-- BASE CENTRALIZADA LLENAR LOS DATOS
USE MEDICITY
SELECT * FROM CIUDAD
INSERT INTO CIUDAD VALUES
('QUITO'),
('AMBATO')

SELECT * FROM PACIENTE
INSERT INTO PACIENTE VALUES
('PACIENTE 1', '1995-01-02 10:00:00', 'CENTRO', 1),
('PACIENTE 2', '1955-11-02 10:00:00', 'NORTE', 2)

SELECT * FROM ESPECIALIDAD
INSERT INTO ESPECIALIDAD VALUES
('ESPECIALIDAD 1'),
('ESPECIALIDAD 2')

SELECT * FROM DOCTOR
INSERT INTO DOCTOR
VALUES ('JUAN',1,1),('ANA',2,2)


SELECT * FROM CITA_MEDICA
INSERT INTO CITA_MEDICA (ID_PACIENTE,ID_DOCTOR,FECHAHORA) 
VALUES (1,2,GETDATE()),(2,1, GETDATE() + DAY(5))

SELECT GETDATE() + DAY(5)

SELECT * FROM DIAGNOSTICO
INSERT INTO DIAGNOSTICO (ID_CITA, NOMBRE, DESCRIPCION, TRATAMIENTO)
VALUES (1,'CITA_1','PACIENTE JOVEN','REPOSO')


SELECT P.NOMBRE PACIENTE, P.FECHA_NACIMIENTO, 
P.DIRECCION, C.NOMBRE CIUDAD_PACIENTE, D.NOMBRE DOCTOR, E.NOMBRE ESPECIALIDAD,
CM.FECHAHORA,
COALESCE(DI.DESCRIPCION,'S/I') DESCRIPCION, COALESCE(DI.TRATAMIENTO,'S/I') TRATAMIENTO
FROM CITA_MEDICA CM
INNER JOIN PACIENTE P ON P.ID = CM.ID_PACIENTE
INNER JOIN DOCTOR D ON D.ID = CM.ID_DOCTOR
INNER JOIN CIUDAD C ON C.ID = P.ID_CIUDAD
INNER JOIN ESPECIALIDAD E ON E.ID = D.ID_ESPECIALIDAD
LEFT JOIN DIAGNOSTICO DI ON DI.ID_CITA = CM.ID


--- MIGRAR DATOS
SELECT * FROM MEDICITY_A.DBO.CIUDAD_SA

INSERT INTO MEDICITY_A.DBO.CIUDAD_SA (NOMBRE)
SELECT NOMBRE FROM MEDICITY.DBO.CIUDAD --CENTRALIZADO

SELECT * FROM MEDICITY_A.DBO.PACIENTE_SA

INSERT INTO MEDICITY_A.DBO.PACIENTE_SA (NOMBRE, FECHA_NACIMIENTO,DIRECCION,ID_CIUDAD)
SELECT NOMBRE, FECHA_NACIMIENTO,DIRECCION,ID_CIUDAD FROM MEDICITY.DBO.PACIENTE --CENTRALIZADO

SELECT * FROM MEDICITY_A.DBO.CITA_MEDICA_SA

INSERT INTO MEDICITY_A.DBO.CITA_MEDICA_SA (ID_PACIENTE, ID_DOCTOR,FECHAHORA)
SELECT ID_PACIENTE, ID_DOCTOR,FECHAHORA FROM MEDICITY.DBO.CITA_MEDICA --CENTRALIZADO
-------------------------------------------
-- MIGRAR INFORMACION DESDE SITIO A AL SITIO B

SELECT * FROM LS_SITIO_B.MEDICITY_B.DBO.ESPECIALIDAD_SB

INSERT INTO LS_SITIO_B.MEDICITY_B.DBO.ESPECIALIDAD_SB (NOMBRE)
SELECT NOMBRE FROM MEDICITY.DBO.ESPECIALIDAD --CENTRALIZADO


SELECT * FROM LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB

INSERT INTO LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB (NOMBRE, ID_ESPECIALIDAD, ID_CIUDAD)
SELECT NOMBRE, ID_ESPECIALIDAD, ID_CIUDAD FROM MEDICITY.DBO.DOCTOR --CENTRALIZADO


SELECT * FROM LS_SITIO_B.MEDICITY_B.DBO.DIAGNOSTICO_SB

INSERT INTO LS_SITIO_B.MEDICITY_B.DBO.DIAGNOSTICO_SB (ID_CITA,NOMBRE, DESCRIPCION, TRATAMIENTO)
SELECT ID_CITA,NOMBRE, DESCRIPCION, TRATAMIENTO FROM MEDICITY.DBO.DIAGNOSTICO --CENTRALIZADO

use medicity_a
----------------------
Create or ALTER VIEW consulta_general AS
SELECT 
    row_number () OVER (ORDER BY CM.FECHAHORA) AS num,
    P.NOMBRE PACIENTE, P.FECHA_NACIMIENTO, P.DIRECCION, 
    C.NOMBRE CIUDAD_PACIENTE, D.NOMBRE DOCTOR, cd.nombre ciudad_doctor, 
    E.NOMBRE ESPECIALIDAD, CM.FECHAHORA,
    COALESCE(DI.DESCRIPCION,'S/I') DESCRIPCION, 
    COALESCE(DI.TRATAMIENTO,'S/I') TRATAMIENTO
FROM MEDICITY_A.DBO.CITA_MEDICA_SA CM
INNER JOIN MEDICITY_A.DBO.PACIENTE_SA P ON P.ID = CM.ID_PACIENTE
INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.DOCTOR_SB D ON D.ID = CM.ID_DOCTOR
INNER JOIN MEDICITY_A.DBO.CIUDAD_SA C ON C.ID = P.ID_CIUDAD
INNER JOIN MEDICITY_A.DBO.CIUDAD_SA CD ON CD.ID = D.ID_CIUDAD
INNER JOIN LS_SITIO_B.MEDICITY_B.DBO.ESPECIALIDAD_SB E ON E.ID = D.ID_ESPECIALIDAD
LEFT JOIN LS_SITIO_B.MEDICITY_B.DBO.DIAGNOSTICO_SB DI ON DI.ID_CITA = CM.ID;
GO


select * from consulta_general

--- sp 

EXEC sp_InsertarDoctor 'LUIS', 1,1

    CREATE OR ALTER PROCEDURE sp_InsertarDoctor
        @NOMBRE VARCHAR(200),
        @ID_ESPECIALIDAD INT,
        @ID_CIUDAD INT
    AS
    BEGIN
        SET NOCOUNT ON;

        -- Validar que exista la ciudad local
        IF NOT EXISTS (
            SELECT 1
            FROM dbo.CIUDAD_SA
            WHERE ID = @ID_CIUDAD
        )
        BEGIN
            RAISERROR('La ciudad ingresada no existe.', 16, 1);
            RETURN;
        END;

        -- Validar que exista la especialidad en Sitio B
        IF NOT EXISTS (
            SELECT 1
            FROM [LS_SITIO_B].[MEDICITY_B].[dbo].[ESPECIALIDAD_SB]
            WHERE ID = @ID_ESPECIALIDAD
        )
        BEGIN
            RAISERROR('La especialidad ingresada no existe.', 16, 1);
            RETURN;
        END;
        INSERT INTO [LS_SITIO_B].[MEDICITY_B].[dbo].[DOCTOR_SB](
            NOMBRE,
            ID_ESPECIALIDAD,
            ID_CIUDAD
        )
        VALUES
        (
            @NOMBRE,
            @ID_ESPECIALIDAD,
            @ID_CIUDAD
        );

        SELECT
            'Doctor registrado correctamente' AS MENSAJE;
    END;
    GO

select * from [LS_SITIO_B].[MEDICITY_B].[dbo].[DOctor_SB]
------------ 
-- update

USE MEDICITY_A;
GO
SELECT * FROM CITA_MEDICA_SA
exec sp_ActualizarCitaMedica 1,2,2,'12/09/2026 10:00:00'

CREATE OR ALTER PROCEDURE sp_ActualizarCitaMedica
    @ID INT,
    @ID_PACIENTE INT,
    @ID_DOCTOR INT,
    @FECHAHORA DATETIME
AS
BEGIN
    SET NOCOUNT ON;

    -- Validar que exista la cita
    IF NOT EXISTS (
        SELECT 1
        FROM dbo.CITA_MEDICA_SA
        WHERE ID = @ID
    )
    BEGIN
        RAISERROR('La cita médica no existe.', 16, 1);
        RETURN;
    END;

    -- Validar fecha
    IF @FECHAHORA < GETDATE()
    BEGIN
        RAISERROR(
            'La fecha y hora de la cita no puede ser anterior a la fecha actual.',
            16,
            1
        );
        RETURN;
    END;

    -- Validar paciente en Sitio B
    IF NOT EXISTS (
        SELECT 1
        FROM [dbo].[PACIENTE_SA]
        WHERE ID = @ID_PACIENTE
    )
    BEGIN
        RAISERROR('El paciente ingresado no existe.', 16, 1);
        RETURN;
    END;

    -- Validar doctor en Sitio B
    IF NOT EXISTS (
        SELECT 1
        FROM [LS_SITIO_B].[MEDICITY_B].[dbo].[DOCTOR_SB]
        WHERE ID = @ID_DOCTOR
    )
    BEGIN
        RAISERROR('El doctor ingresado no existe.', 16, 1);
        RETURN;
    END;

    -- Actualizar
    UPDATE dbo.CITA_MEDICA_SA
    SET
        ID_PACIENTE = @ID_PACIENTE,
        ID_DOCTOR = @ID_DOCTOR,
        FECHAHORA = @FECHAHORA
    WHERE ID = @ID;
END;
GO

----CREAR DOCTOR
USE MEDICITY_A;
GO

SELECT * FROM [LS_SITIO_B].[MEDICITY_B].[dbo].[DOCTOR_SB];

CREATE OR ALTER VIEW vw_Doctores_SitioA AS
SELECT 
    D.ID AS DoctorID,
    D.NOMBRE AS NombreDoctor,
    E.NOMBRE AS Especialidad,
    C.NOMBRE AS Ciudad
FROM 
    [LS_SITIO_B].[MEDICITY_B].[dbo].[DOCTOR_SB] D
INNER JOIN 
    [LS_SITIO_B].[MEDICITY_B].[dbo].[ESPECIALIDAD_SB] E ON D.ID_ESPECIALIDAD = E.ID
INNER JOIN 
    dbo.CIUDAD_SA C ON D.ID_CIUDAD = C.ID;
GO

SELECT * FROM vw_Doctores_SitioA;

--VISTA ACTUALIZAR CITA
USE MEDICITY_A;
GO

CREATE OR ALTER VIEW vw_Citas_Actualizadas AS
SELECT
 CM.ID AS CitaID,
 P.NOMBRE AS Paciente,
 D.NOMBRE AS Doctor,
 CM.FECHAHORA AS FechaCita
FROM
 dbo.CITA_MEDICA_SA CM
INNER JOIN dbo.PACIENTE_SA P ON CM.ID_PACIENTE = P.ID
INNER JOIN [LS_SITIO_B].[MEDICITY_B].[dbo].[DOCTOR_SB] D ON CM.ID_DOCTOR = D.ID;
GO

SELECT * FROM vw_Citas_Actualizadas;

--SP Actualizar Pacientes
USE MEDICITY_A;
GO

CREATE OR ALTER PROCEDURE sp_ActualizarPaciente
    @ID INT,
    @NOMBRE VARCHAR(200),
    @FECHA_NACIMIENTO DATETIME,
    @DIRECCION VARCHAR(200),
    @ID_CIUDAD INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.PACIENTE_SA
        WHERE ID = @ID
    )
    BEGIN
        RAISERROR('El paciente no existe.', 16, 1);
        RETURN;
    END;
    IF NOT EXISTS (
        SELECT 1
        FROM dbo.CIUDAD_SA
        WHERE ID = @ID_CIUDAD
    )
    BEGIN
        RAISERROR('La ciudad ingresada no existe.', 16, 1);
        RETURN;
    END;
    UPDATE dbo.PACIENTE_SA
    SET
        NOMBRE = @NOMBRE,
        FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
        DIRECCION = @DIRECCION,
        ID_CIUDAD = @ID_CIUDAD
    WHERE ID = @ID;
    SELECT 'Paciente actualizado correctamente' AS MENSAJE;
    END;
    GO

--Vista actualizar pacientes

EXEC sp_ActualizarPaciente 1, 'MARTA', '1990-01-01', 'SUR', 2;
CREATE OR ALTER VIEW vw_Pacientes_SitioA AS
    SELECT 
        P.ID,
        P.NOMBRE AS Paciente,
        P.FECHA_NACIMIENTO,
        P.DIRECCION,
        C.NOMBRE AS Ciudad
    FROM
     dbo.PACIENTE_SA P
    INNER JOIN
     dbo.CIUDAD_SA C ON P.ID_CIUDAD = C.ID;
GO

SELECT * FROM vw_Pacientes_SitioA;
----NUEVA ESPECIALIDAD
USE MEDICITY_A;
GO

CREATE OR ALTER PROCEDURE sp_InsertarEspecialidad
    @NOMBRE VARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [LS_SITIO_B].[MEDICITY_B].[dbo].[ESPECIALIDAD_SB] (NOMBRE)
    VALUES (@NOMBRE);
    
    SELECT 'Especialidad registrada correctamente' AS MENSAJE;
END;
GO


EXEC sp_InsertarEspecialidad 'CARDIOLOGIA';

--VISTA ESPECIALIDAD
CREATE OR ALTER VIEW vw_Especialidades_SitioB AS
SELECT 
    ID,
    NOMBRE AS Especialidad
FROM 
 [LS_SITIO_B].[MEDICITY_B].[dbo].[ESPECIALIDAD_SB];
GO

SELECT * FROM vw_Especialidades_SitioB;


select * from CITA_MEDICA_SA;
select * from PACIENTE_SA;
select * from [LS_SITIO_B].[MEDICITY_B].[dbo].[ESPECIALIDAD_SB]